// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/Action.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    TimeSchedule: typeof import('./src/components/TimeSchedule.vue')['default']
    TimezoneSearch: typeof import('./src/components/TimezoneSearch.vue')['default']
  }
}
